apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: codexctl
  name: codexctl-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: codexctl-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    # trunk-ignore(checkov/CKV_SECRET_6): Secret name and SSM path only. No secret value.
    - secretKey: vault-key
      remoteRef:
        key: /app/codexctl/vault-key
        decodingStrategy: Base64
    # trunk-ignore(checkov/CKV_SECRET_6): Secret name and SSM path only. No secret value.
    - secretKey: oidc-client-secret
      remoteRef:
        key: /app/codexctl/oidc-client-secret
    # trunk-ignore(checkov/CKV_SECRET_6): Secret name and SSM path only. No secret value.
    - secretKey: metrics-token
      remoteRef:
        key: /app/codexctl/metrics-token
