apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codexctl
resources:
  - ../../rds-ca
  - ../../base
  - ingress.yaml
  - externalsecret.yaml
  - sso.yaml
  - monitoring.yaml
  - migration-networkpolicy.yaml
images:
  - name: codexctl-central
    newName: 767398060436.dkr.ecr.us-east-1.amazonaws.com/codexctl-central
    digest: sha256:33f5bea3efd4ec81735315040d2cfe28b0bb901ac7d3d2d7cb6935f2070251ef
patches:
  - path: codexctl-restart-patch.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: codexctl
      namespace: codexctl
