apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codexctl
resources:
  - ../../base
  - ingress.yaml
  - externalsecret.yaml
  - sso.yaml
  - monitoring.yaml
images:
  - name: codexctl-central
    newName: 767398060436.dkr.ecr.us-east-1.amazonaws.com/codexctl-central
    digest: sha256:7c442a3ced9bf906ffc2ffa38d97d199761810c70a2299ba18bd514eacce419f
