apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codexctl
resources:
  - ../../rds-ca
  - ../../base
  - ingress.yaml
  - externalsecret.yaml
  - sso.yaml
  - monitoring.yaml
  - migration-networkpolicy.yaml
images:
  - name: codexctl-central
    newName: 767398060436.dkr.ecr.us-east-1.amazonaws.com/codexctl-central
    digest: sha256:b55a6a99b07faef0feb4cd9503bb7f0f79b098926e09ab2753abb77d51adf9f0
patches:
  - path: codexctl-restart-patch.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: codexctl
      namespace: codexctl
