apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codexctl
resources:
  - ../../rds-ca
  - namespace.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - migration-networkpolicy.yaml
  - sso.yaml
  - codexctl-externalsecret.yaml
  - deployment.yaml
  - pdb.yaml
  - monitoring.yaml
images:
  - name: codexctl-central
    newName: 767398060436.dkr.ecr.us-east-1.amazonaws.com/codexctl-central
    digest: sha256:f67698fe7de7e35eb3659f98a358552edbe1b1d5b52147a4645f25cfa11b0273
