apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codexctl
resources:
  - namespace.yaml
  - service.yaml
  - networkpolicy.yaml
  - sso.yaml
  - codexctl-externalsecret.yaml
  - deployment.yaml
  - pdb.yaml
  - postgres-externalsecret.yaml
