apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codexctl-postgres
  namespace: codexctl
spec:
  refreshInterval: 1h
  secretStoreRef: { name: aws-parameter-store, kind: ClusterSecretStore }
  target: { name: codexctl-postgres, creationPolicy: Owner }
  data:
    # trunk-ignore(checkov/CKV_SECRET_6): Secret name and SSM path only. No secret value.
    - {
        secretKey: db-hostname,
        remoteRef: { key: /rds/quota-manager/codexctl/db_hostname },
      }
    # trunk-ignore(checkov/CKV_SECRET_6): Secret name and SSM path only. No secret value.
    - {
        secretKey: db-port,
        remoteRef: { key: /rds/quota-manager/codexctl/db_port },
      }
    # trunk-ignore(checkov/CKV_SECRET_6): Secret name and SSM path only. No secret value.
    - {
        secretKey: db-name,
        remoteRef: { key: /rds/quota-manager/codexctl/db_name },
      }
    # trunk-ignore(checkov/CKV_SECRET_6): Secret name and SSM path only. No secret value.
    - {
        secretKey: db-user,
        remoteRef: { key: /rds/quota-manager/codexctl/db_user },
      }
    # trunk-ignore(checkov/CKV_SECRET_6): Secret name and SSM path only. No secret value.
    - {
        secretKey: db-password,
        remoteRef: { key: /rds/quota-manager/codexctl/db_password },
      }
