apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codexctl-postgres
  namespace: codexctl
spec:
  refreshInterval: 1h
  secretStoreRef: {name: aws-parameter-store, kind: ClusterSecretStore}
  target: {name: codexctl-postgres, creationPolicy: Owner}
  data:
    - {secretKey: db-hostname, remoteRef: {key: /rds/quota-manager/codexctl/db_hostname}}
    - {secretKey: db-port, remoteRef: {key: /rds/quota-manager/codexctl/db_port}}
    - {secretKey: db-name, remoteRef: {key: /rds/quota-manager/codexctl/db_name}}
    - {secretKey: db-user, remoteRef: {key: /rds/quota-manager/codexctl/db_user}}
    - {secretKey: db-password, remoteRef: {key: /rds/quota-manager/codexctl/db_password}}
