apiVersion: v1
kind: ConfigMap
metadata:
  namespace: codexctl
  name: codexctl-sso
data:
  sso.json: |
    {
      "issuer": "https://clerk.sawmills.ai",
      "client_id": "StnV91x99CEYVmSy",
      "client_secret_file": "/keys/oidc-client-secret",
      "allowed_domains": ["sawmills.ai"]
    }
