name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets

      - name: Test
        run: cargo test --all-targets

      - name: Build
        run: cargo build --release

  trunk:
    name: Trunk Check
    # trunk-ignore(actionlint/runner-label): Namespace profile
    runs-on: namespace-profile-sawmills-runner-large
    steps:
      - uses: actions/checkout@v4
      - name: Cache Trunk and Rust artifacts
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        # yamllint disable-line rule:line-length
        uses: namespacelabs/nscloud-cache-action@15799a6b54e5765f85b2aac25b3f0df43ed571c0
        with:
          cache: rust
          path: |
            /home/runner/.cache/trunk
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          cache: false
          check-mode: ${{ github.event_name == 'pull_request' && 'pull_request' || 'all' }}

  build-macos:
    name: Build (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --all-targets
